export const LEGACY_COMMAND_REPLACEMENTS: Record<string, string | null> = {
  add: 'app add',
  apply: 'app apply',
  build: 'app build',
  'catalog-sync': null,
  deploy: null,
  dev: 'app dev',
  exec: 'app exec',
  install: 'app install',
  logs: 'app logs',
  plan: 'app plan',
  publish: 'app publish',
  pull: 'app pull',
  server: 'local',
  typecheck: 'app typecheck',
  uninstall: 'app uninstall',
  'app:install': 'app install',
  'app:publish': 'app publish',
  'app:uninstall': 'app uninstall',
  'dev:add': 'app add',
  'dev:build': 'app build',
  'dev:catalog-sync': null,
  'dev:function:exec': 'app exec',
  'dev:function:logs': 'app logs',
  'dev:generate-client': null,
  'dev:translations-extract': null,
  'dev:typecheck': 'app typecheck',
  'docker:logs': 'local logs',
  'docker:reset': 'local reset',
  'docker:start': 'local start',
  'docker:status': 'local status',
  'docker:stop': 'local stop',
  'docker:upgrade': null,
  'remote add': 'auth login',
  'remote status': 'auth status',
  'remote switch': 'remote use',
  'remote:add': 'auth login',
  'remote:list': 'remote list',
  'remote:remove': 'remote remove',
  'remote:status': 'auth status',
  'remote:use': 'remote use',
};
